import uuid
from datetime import datetime
from mongoengine import Document, StringField, DateTimeField, UUIDField, ListField, DictField

class LearningPlan(Document):
    """
    Personalized learning plan generated by the Recommendation Agent.
    """
    plan_id = UUIDField(primary_key=True, default=uuid.uuid4)
    employee_id = StringField(required=True)  # UUID string ref to Employee
    assessment_id = StringField(required=True)  # UUID string ref to SkillAssessment
    
    # List of recommended module IDs with reasoning
    # [{"module_id": "...", "reasoning": "Addresses weak area in Python"}]
    recommended_modules = ListField(DictField(), default=list)
    
    created_by_model = StringField(required=True)
    created_at = DateTimeField(default=datetime.utcnow)
    updated_at = DateTimeField(default=datetime.utcnow)
    
    meta = {
        'collection': 'learning_plans',
        'indexes': ['employee_id', 'assessment_id'],
        'ordering': ['-created_at'],
    }
