import uuid
from datetime import datetime
from mongoengine import Document, StringField, FloatField, DictField, DateTimeField, UUIDField

class Report(Document):
    """
    Analytics report generated by the Analytics Agent.
    Can be for an individual employee, a department, or org-wide.
    """
    report_id = UUIDField(primary_key=True, default=uuid.uuid4)
    report_type = StringField(choices=('individual', 'department', 'org'), required=True)
    employee_id = StringField(required=False, null=True)
    department_id = StringField(required=False, null=True)
    
    # Aggregated metrics
    performance_score = FloatField(default=0.0)
    completion_percentage = FloatField(default=0.0)
    metrics = DictField(default=dict)
    feedback = StringField(required=False, allow_blank=True)
    
    generated_at = DateTimeField(default=datetime.utcnow)

    meta = {
        'collection': 'analytics_reports',
        'indexes': ['report_type', 'employee_id', 'department_id', '-generated_at'],
        'ordering': ['-generated_at'],
    }
