import uuid
from datetime import datetime
from mongoengine import (
    Document, StringField, FloatField, ListField, 
    DateTimeField, UUIDField, DictField, IntField
)


class SkillAssessment(Document):
    """
    Represents a single skill assessment taken by an employee.
    Multiple assessments per employee are allowed to track progression over time.
    """
    ASSESSMENT_STATUS_CHOICES = ('pending', 'in_progress', 'completed', 'expired')

    assessment_id = UUIDField(primary_key=True, default=uuid.uuid4)
    employee_id = StringField(required=True)  # UUID string ref to Employee
    
    # Assessment metadata
    title = StringField(required=True, max_length=255)
    description = StringField(max_length=1000, default='')
    
    # Questions are stored as a list of dicts:
    # [{ "question_id": "q1", "text": "...", "options": ["A","B","C","D"], "correct_answer": "B", "category": "python" }]
    questions = ListField(DictField(), default=list)
    
    # Answers submitted by the employee:
    # [{ "question_id": "q1", "selected_answer": "A" }]
    answers = ListField(DictField(), default=list)
    
    # Results (populated after scoring)
    skill_score = FloatField(default=0.0)  # 0.0 to 100.0
    max_score = FloatField(default=100.0)
    weak_areas = ListField(StringField(), default=list)
    strong_areas = ListField(StringField(), default=list)
    
    # Category-level breakdown: { "python": 60.0, "sql": 80.0, "communication": 40.0 }
    category_scores = DictField(default=dict)
    
    status = StringField(
        required=True, 
        choices=ASSESSMENT_STATUS_CHOICES, 
        default='pending'
    )
    
    # Trigger event reference (for idempotency)
    trigger_event_id = StringField(null=True)
    
    created_at = DateTimeField(default=datetime.utcnow)
    completed_at = DateTimeField(null=True)
    
    meta = {
        'collection': 'skill_assessments',
        'indexes': ['employee_id', 'status', 'trigger_event_id'],
        'ordering': ['-created_at'],
    }


class AssessmentTemplate(Document):
    """
    Reusable assessment templates tied to job roles.
    Pre-seeded by HR or generated by LLM based on role requirements.
    """
    template_id = UUIDField(primary_key=True, default=uuid.uuid4)
    role = StringField(required=True, max_length=100)  # e.g. "software_engineer", "data_analyst"
    title = StringField(required=True, max_length=255)
    description = StringField(max_length=1000, default='')
    
    # Template questions (same schema as SkillAssessment.questions)
    questions = ListField(DictField(), default=list)
    
    # Metadata
    difficulty = StringField(choices=('beginner', 'intermediate', 'advanced'), default='intermediate')
    time_limit_minutes = IntField(default=30)
    categories = ListField(StringField(), default=list)  # e.g. ["python", "sql", "system_design"]
    
    created_at = DateTimeField(default=datetime.utcnow)
    updated_at = DateTimeField(default=datetime.utcnow)
    
    meta = {
        'collection': 'assessment_templates',
        'indexes': ['role'],
    }
